version: "{build}"

os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

platform:
  - x64
  - x86

install:
  - ps: Install-Product node 8.9.4 $env:platform
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - cmd: npm install

# disable build and test pahses
test:
  - cmd: npm run test
